name: tddboilerplate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependency_overrides:
  intl: ^0.18.1
  analyzer: ^6.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

  # Functional programming thingies
  dartz: ^0.10.1

  # Use as Network Client
  dio: ^5.3.2

  # Use hive to save local data
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Use for Dependencies Injection
  get_it: ^7.6.4

  # Use for State Management with BLoC pattern
  flutter_bloc: ^8.1.3


  # Use for custom toast with Status, ex : Loading,Success,Failed
  oktoast: ^3.3.1

  # Use for responsive UI, set default size base on Mock Up
  flutter_screenutil: ^5.9.0

  cached_network_image: ^3.2.3

  # logger
  logger: ^2.0.2

  # Firebase
  firebase_core: ^2.16.0
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6

  # router
  go_router: ^10.2.0

  # Freezed
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  lint: ^2.1.2
  flutter_lints: ^2.0.3
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  http_mock_adapter: ^0.6.0

  #Temporary using old version because error when generate build_runner
  mockito: ^5.4.2

  # Freezed
  freezed: ^2.4.2
  json_serializable: ^6.7.1

  # hive generator
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
